import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

//ui
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";

const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Dental-clinic-system",
  description: "Generated by Poraparint",
  icons: "/favicon.ico",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <SessionProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${kanit.className} antialiased `}>
          
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            {children}
            </ThemeProvider>
          
        </body>
      </html>
    </SessionProvider>
  );
}
