import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

//providers
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

//cookies
import { cookies } from "next/headers";

//next-themes
import { ThemeProvider } from "@/theme/theme-provider";

//ui
import { Toaster } from "@/components/ui/sonner";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/components/app-sidebar";
import { Navbar } from "./components/navbar";

const kanit = Kanit({
  subsets: ["thai", "latin"],
  weight: ["200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Dental-clinic-system",
  description: "Generated by Poraparint",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${kanit.className} antialiased flex h-screen overflow-hidden`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider defaultOpen={defaultOpen}>
              <div className="flex w-screen h-full">
                {/* Sidebar */}
                <AppSidebar />

                {/* Main Content */}
                <main className="flex flex-1 flex-col overflow-auto">
                  <Navbar />
                  <Toaster/>
                  <div className="p-4">{children}</div>
                </main>
              </div>
            </SidebarProvider>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
